### ISSUE TITLE
GET routes defined with POST

### ISSUE THREAD

**Issue by cchauche** [FEC-hr-nyc36/catwalk#51]
https://github.com/FEC-hr-nyc36/catwalk/blob/a7aca023a7aea0b8e6640c9e7b10cea622194a5a/server/routes/routes.js#L4-L7

If I'm understanding the code correctly it looks like the `/api` routes to all use HTTP POST method.  This means that on the client side you have to use POST requests to request data from the server.  While this does work it adds a layer of confusion since the REST API conventions require that POST routes only be used for routes that are creating new resources.  If your `/api` routes are not creating new resources and instead are retrieving data then the GET method should be used.   

You can reference this website for guidance on when to use what method: https://restfulapi.net/http-methods/

**Comment by kennyctran** [comment]
This is done and tests were changed to document the change!
